### ISSUE TITLE
[Please HELP] I just want to use at Wordpress, so how to do it

### ISSUE THREAD

**Issue by mkvtvseries** [biohzrdmx/jQuery.LazyTube#1]
Hello, Is it possible to use for some video hosting iframe other than youtube?
And show data-thumbnail with featured image..
As I need a Wordpress plugin...

**Comment by biohzrdmx** [comment]
Hi, it should be possible to use any service as long as it just requires an embedded iframe but that will require some work as the default embed code is hardcoded (a callback will be useful for this). Also the thumbnails are automatically extracted, so another callback would do the trick. For the WordPress thing there is no explicit need for a plugin, as it is possible to just include the JS file:
```php
// In functions.php locate the part that enqueues scripts and add this line, customizing the location of jquery.lazytube.min.js
wp_enqueue_script('jquery.lazytube', get_template_directory_uri() . '/js/jquery.lazytube.min.js', ['jquery']);
```
And use a selector for all your videos, then with jQuery call the `$.fn.lazyTube` function for all the matching elements, as per the documentation:
```javascript
jQuery(document).ready(function($) {
    $('.video').lazyTube({
        // Here goes the extra stuff to support other providers
    });
});
```
I can modify the core logic to allow other services and the thumbnail thing, but for now a tighter WordPress integration is out of scope as it is not really required and surely will just bloat your WP instance with another plugin.

It should be ready later today, please stay tuned!

**Comment by mkvtvseries** [comment]
Thank you.. Is there a way I can communicate with you?

**Comment by biohzrdmx** [comment]
Hi again, the code has been updated. I added support for two callbacks to provide the markup for the embed code and the image preview, also I added an example for Vimeo (https://github.com/biohzrdmx/jQuery.LazyTube#other-services). I think it should be a good starting point to adapt it to any service.

You may contact me by using this form if you like: https://biohzrdmx.me/contact

Hope you find this plugin useful!

**Comment by mkvtvseries** [comment]
Hi, did u get my msg? While trying to send msg through ur contact page.. As it doesn't show success.. so i was confused.. did it really send or not?

**Comment by biohzrdmx** [comment]
Hi, I just replied to your message via email, there was en error on the contact form, so thanks for reporting!
